### ISSUE TITLE
Error on all Projects

### ISSUE THREAD

**Issue by LunarPunks** [radicleart/clarity-market#10]
Hi, i cannot seem to test any of your projects except AppMap

They all get the same error:

loopbomb-genesis:108:6: error: use of unresolved contract 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.loopbomb-stx-v1'

Can you help please, I am using clarinet on Visual Studio Code.

Thank You

**Comment by dcsan** [comment]
(not my repo but...)
ST sounds like a contract on testnet, are you trying to deploy there? 
check if that contract exists

**Comment by LunarPunks** [comment]
I have the full repo and just running clarinet check and it comes up with this error, the ST address is a local address is from devnet.toml

What i am doing wrong, normally i just get a repo and it just works, these one's i am confused?

**Comment by radicleart** [comment]
@LunarPunks thanks for reporting the tests are working now.

**Comment by radicleart** [comment]
@LunarPunks you should be able to cd into the individual projects and run clarinet commands there.

**Comment by LunarPunks** [comment]
Hi Mike, Thanks for getting back to me,  unfortunately getting exact same error.

Do i need to make any changes locally?

**Comment by LunarPunks** [comment]
loopbomb-genesis:108:6: error: use of unresolved contract 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.loopbomb-stx-v1'

**Comment by LunarPunks** [comment]
PS C:\wamp64\www\web3\clarity-market\projects\loopbomb> clarinet check

loopbomb-stx-v1:694:34: error: incorrect number of arguments in call to 'record-bid' (expected 4 got 5)
                        (unwrap! (record-bid nftIndex nextBidAmount currentBidIndex  block-height saleCycle) failed-to-stx-transfer)
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
loopbomb-genesis:108:6: error: use of unresolved contract 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.loopbomb-stx-v1'
    (begin
     ^~~~~
  loopbomb-genesis:110:9:
        (try! (contract-call? .loopbomb-stx-v1 burn id contract-caller))
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  loopbomb-genesis:113:9:
        (try! (nft-mint? loopbomb id contract-caller))
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  loopbomb-genesis:114:9:
        (ok true)
        ^~~~~~~~~

**Comment by radicleart** [comment]
Thanks.. double checking your on `main` branch and commit:
 corrected clarinet tests and removed unused projects	ff8b6cd

my output...

```clarity-market/projects/loopbomb$ clarinet test

Running file:///Users/mikey/hubgit/radicle-solutions/loopbomb-dev/clarity-market/projects/loopbomb/tests/loopbomb-stx-v1_test.ts
* Loopbomb - test variables of contract ... ok (86ms)
Running file:///Users/mikey/hubgit/radicle-solutions/loopbomb-dev/clarity-market/projects/loopbomb/tests/loopbomb-genesis_test.ts
* Loopbomb - test transfer-administrator ... ok (102ms)
* Loopbomb - test update-mint-price ... ok (119ms)
* Loopbomb - test get-balance ... ok (91ms)
* Loopbomb - transfer-balance ... ok (114ms)
* Loopbomb - test collection-mint-token ... ok (163ms)
* Loopbomb - test collection-mint-token-twenty ... ok (468ms)
* LoopbombV2 - Ensure can upgrade v1 -> v2 ... ok (1375ms)
* Loopbomb - test transfer ... ok (454ms)
* Loopbomb - test buy now ... ok (153ms)
* LoopbombV2 - Ensure can list and unlist by owner ... ok (293ms)
* LoopbombV2 - Ensure can NFT be listed and bought ... ok (106ms)
* LoopbombV2 - Ensure that NFT can't be bought with different commission trait ... ok (102ms)
* LoopbombV2 - Ensure NFT can't be bought when unlisted ... ok (118ms)
* LoopbombV2 - Ensure NFT can't be transferred when listed ... ok (104ms)
* LoopbombV2 - ensure cannot mint v2 ... ok (25ms)
* LoopbombV2 - test admin airdrop ... ok (39ms)
* LoopbombV2 - Ensure can freeze metadata ... ok (69ms)
* LoopbombV2 - ensure can burn ... ok (92ms)
* LoopbombV2 - Ensure can transfer administrator ... ok (42ms)
* LoopbombV2 - ensure can give approval ... ok (117ms)
* LoopbombV2 - ensure can give and remove approval ... ok (117ms)
* LoopbombV2 - ensure can approve all ... ok (154ms)
* LoopbombV2 - ensure can approve all but block specified nft ... ok (160ms)

test result: ok. 24 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (4149ms)```

**Comment by LunarPunks** [comment]
Hi, sorry same, i  deleted everything and cloned the main repo,  can it possible be variable linked to you local setup? I am sure it something very simple, i cannot work it out.  Same using clarinet check OR clarinet test:

I have been on the stack chat and they keep telling me maybe the sip09 contract is not present, but we know it is. Please help

loopbomb-stx-v1:694:34: error: incorrect number of arguments in call to 'record-bid' (expected 4 got 5)
                        (unwrap! (record-bid nftIndex nextBidAmount currentBidIndex  block-height saleCycle) failed-to-stx-transfer)
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
loopbomb-genesis:108:6: error: use of unresolved contract 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.loopbomb-stx-v1'
    (begin
     ^~~~~
  loopbomb-genesis:110:9:
        (try! (contract-call? .loopbomb-stx-v1 burn id contract-caller))
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  loopbomb-genesis:113:9:
        (try! (nft-mint? loopbomb id contract-caller))
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  loopbomb-genesis:114:9:
        (ok true)

**Comment by LunarPunks** [comment]
Any Tips?

**Comment by radicleart** [comment]
I will take a look tomorrow - its odd the tests behave differently in your environment.Are you on a mac or pc?

**Comment by radicleart** [comment]
Maybe its the Clarinet version ?

mine is..

```$ clarinet -V
clarinet 0.17.0
```

**Comment by radicleart** [comment]
@LunarPunks thanks for bearing with me - I just ran brew upgrade clarinet and found the problem you were seeing.

Should be fixed now?

**Comment by LunarPunks** [comment]
Ah You are superstar,   it works great now.

Lol hope I am not pushing my luck, do you by any chance have any frontend integration for Loopbomb? this will really jumpstart my web3 learning experience,

**Comment by radicleart** [comment]
Yes - its a bit complex atm as we are about to run the upgrade from the loopbomb-stx-v1 to the loopbomb-genesis contract. So we currently have
mainnet: https://loopbomb.io                   --> loopbomb-stx-v1
testnet:   https://staging.loopbomb.io     --> loopbomb-genesis

The best place to play around is https://staging.stacksmate.com which is an independent marketplace on testnet.

**Comment by LunarPunks** [comment]
Thank You so much.

If in the future you have some skeleton code which one can use for frontend integration with hiro wallet on devnet, please do let me know.

Thanks Again
